elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
# logstash:
#   image: logstash:latest
#   # command: logstash -f /etc/logstash/conf.d/logstash.conf
#   command: /bin/bash
#   tty: true
#   volumes:
#     - ./logstash/config:/etc/logstash/conf.d
#   ports:
#     - "5000:5000"
#   links:
#     - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch

fluentd:
  build: prod-fluentd
  # tty: true
  # command: /bin/sh
  ports:
    - "24224:24224"
